mysql:
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:hudsonof47}
  url: ${MYSQL_URL:localhost:3306}
  schema: catalog_admin

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none